Auto import backends in `triton.language.extra`
Before 53166efa2494764e11734d57de681cc4d2486981, importing
triton/language/extra/__init__.py used to import cuda and hip.

After the commit it no longer imports them because submodules in
triton.language.extra are moved to /third_party and copied during
setup.py. This change breaks code that relies on such behavior:

```python
from triton.language import extra
extra.cuda
>>> <cuda submodule>

from triton.language import extra
extra.cuda

>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'triton.language.extra' has no attribute 'cuda'
```

To keep the compatibility, this commit is to dynamically import
submodules in `triton.language.extra`.